### ISSUE TITLE
HF Space is down / has runtime error

### ISSUE THREAD

**Issue by Glavin001** [shon-otmazgin/fastcoref#42]
See https://huggingface.co/spaces/pythiccoder/FastCoref

![image](https://github.com/shon-otmazgin/fastcoref/assets/1885333/7935d0ca-05d9-4505-a2b4-e2310c2d17de)

```
Runtime error
Space failed. Exit code: 1. Reason: Traceback (most recent call last):
  File "app.py", line 2, in <module>
    import spacy
  File "/home/user/.local/lib/python3.8/site-packages/spacy/__init__.py", line 14, in <module>
    from . import pipeline  # noqa: F401
  File "/home/user/.local/lib/python3.8/site-packages/spacy/pipeline/__init__.py", line 1, in <module>
    from .attributeruler import AttributeRuler
  File "/home/user/.local/lib/python3.8/site-packages/spacy/pipeline/attributeruler.py", line 6, in <module>
    from .pipe import Pipe
  File "spacy/pipeline/pipe.pyx", line 1, in init spacy.pipeline.pipe
  File "spacy/vocab.pyx", line 1, in init spacy.vocab
  File "/home/user/.local/lib/python3.8/site-packages/spacy/tokens/__init__.py", line 1, in <module>
    from .doc import Doc
  File "spacy/tokens/doc.pyx", line 36, in init spacy.tokens.doc
  File "/home/user/.local/lib/python3.8/site-packages/spacy/schemas.py", line 222, in <module>
    class TokenPattern(BaseModel):
  File "pydantic/main.py", line 205, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 491, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 421, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 537, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 634, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 641, in pydantic.fields.ModelField._type_analysis
  File "/usr/local/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```

**Comment by shon-otmazgin** [comment]
hello, can you try to open the issue there? I mean at the HF page?

**Comment by Glavin001** [comment]
OK, done: https://huggingface.co/spaces/pythiccoder/FastCoref/discussions/3
